INSERT INTO PUBLIC."ROLE" (ID, LABEL) VALUES(1, 'RESP') ;
INSERT INTO PUBLIC."ROLE" (ID, LABEL) VALUES(2, 'ADMIN');
INSERT INTO PUBLIC."ROLE" (ID, LABEL) VALUES(3, 'ANIM');
INSERT INTO PUBLIC."ROLE" (ID, LABEL) VALUES(4, 'CLIENT');
INSERT INTO PUBLIC."ROLE" (ID, LABEL) VALUES(5, 'VIP');

INSERT INTO PUBLIC."TYPE_SALLE" (ID, LABEL) VALUES(1, 'CINEMA');

INSERT INTO PUBLIC."SALLE" (ID, LABEL) VALUES(1, 'GAUMONT');

